#!/usr/bin/env bash
# fix curl port 80 issues
apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
