#!/usr/bin/env bash
# fix curl port 80 issues
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                              
rm default;                                                                                           
ln -s /etc/nginx/sites-available/default default;                                                                                                                                           
service nginx restart 
