#!/usr/bin/env bash
# displays To infinity and beyond and print I am invincible!!! on SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
