#!/usr/bin/env bash
# writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program pause for 2 seconds

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
